BACKGROUND_COLOR = (50, 50, 50)
BLACK = (0, 0, 0)
GREEN = (0, 255, 0)
WHITE = (250, 250, 250)
DARK_GREEN = (50, 100, 50)

CELL_SIZE = 12
ANT_SIZE = CELL_SIZE - 4
ENVIROMENT_SIZE = 50

SCREEN_MARGIN = 2
SCREEN_SIZE = (CELL_SIZE*ENVIROMENT_SIZE + SCREEN_MARGIN, CELL_SIZE*ENVIROMENT_SIZE + SCREEN_MARGIN)

ALIVE_ANTS_NUM = 50
DEAD_ANTS_NUM = 500

NEW_POSITIONS_POSSIBILITIES = 8

status = {
	"dead_ant": -1,
	"empty": 0,
	"available_ant": 1,
	"alive_overlap_dead": 2
}